# Pandas

Install Pandas using `pip install pandas` on terminal.

import the library as pd (this is the standard)

In [2]:
import pandas as pd

## CSV

- reading a csv file

In [3]:
df = pd.read_csv('movies.csv')

df - dataframe is a data structure provided by pandas to store 2d tabels with labels

- Display first five rows

In [4]:
df.head()

df.head(2) # displays the first 2 rows of the DataFrame

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English

- Display last five rows

In [5]:
df.tail() # displays the last 5 rows of the DataFrame

df.tail(3) # displays the last 3 rows of the DataFrame

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

- Display random(sample) rows

In [6]:
df.sample()

df.sample(3) # displays 3 random rows from the DataFrame

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English

- Get rows and cols (shape)

In [7]:
df.shape # returns the number of rows and columns in the DataFrame as a tuple (rows, columns)

(37, 10)

- Display all cols

In [8]:
df.columns # returns the column names of the DataFrame as an Index object

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='str')

In [9]:
df.count() # returns the number of non-null values in each column of the DataFrame

title           37
industry        37
release_year    37
imdb_rating     36
studio          34
budget          37
revenue         37
unit            37
currency        37
language        37
dtype: int64

- find how many different types of industries we have in our movies df

In [10]:
df.industry.unique() # returns the unique values in the 'industry' column of the DataFrame

<StringArray>
['Bollywood', 'Hollywood']
Length: 2, dtype: str

- find how many movies in each

In [11]:
df.industry.value_counts() # returns the count of unique values in the 'industry' column of the DataFrame

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

- Find min, max, mean, etc

In [12]:
df.imdb_rating.min() # returns the minimum value in the 'imdb_rating' column of the DataFrame
df.imdb_rating.max() # returns the maximum value in the 'imdb_rating' column of the DataFrame
df.imdb_rating.mean() # returns the mean (average) of the 'imdb_rating' column in the DataFrame
df.imdb_rating.median() # returns the median of the 'imdb_rating' column in the DataFrame

np.float64(8.1)

- Display movies released between 2000 and 2010

In [13]:
df[(df.release_year > 2000) & (df.release_year < 2010)] # filters the DataFrame to include only rows where the 'release_year' column is greater than 2000 and less than 2010

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

- Display all marvel movies

In [14]:
df[df.studio == 'Marvel Studios'] # filters the DataFrame to include only rows where the 'studio' column is equal to 'Marvel Studios'

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

- Add a new col called profit(difference between  revenue and budget)

In [15]:
df["profit"] = df.revenue - df.budget # creates a new column 'profit' by subtracting the 'budget' column from the 'revenue' column in the DataFrame
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,420.0

- Add a col called age (current year - release year)

In [16]:
df["age"] = 2026 - df.release_year # creates a new column 'age' by subtracting the 'release_year' column from the current year (2024) in the DataFrame
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,30000.0,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,754.8,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,479.8,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,674.0,9
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,420.0,4

- Find out if any row contains  Null value

In [17]:
df[df.isnull().any(axis=1)] # returns rows with any null values in the DataFrame

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,profit,age
16,Parasite,Hollywood,2019,8.5,NaN,15.5,263.1,Millions,USD,English,247.6,7
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi,2.1,11
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi,1230.0,19
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi,4.9,8

-  We have added new cols, now lets create a new csv file which contains all the updated info

In [18]:
df.to_csv('movies_with_profit_and_age.csv', index=False) # saves the DataFrame to a new CSV file named 'movies_with_profit_and_age.csv' without including the index column

## EXCEL

we have a file called  `movies_db.xlsx `, lets read this file and do some operations with it

Install an extention to read excel files `pip install openpyxl`

read the file and store it in a dataframe

In [19]:
df_movies_db = pd.read_excel('movies_db.xlsx') # reads an Excel file named 'movies_db.xlsx' into a new DataFrame called df_movies_db

df_movies_db.head() # displays the first 5 rows of the df_movies_db DataFrame

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

if we see the excel file we can see that it has multiple sheets,

In [20]:
df_movies_db_sheet2 = pd.read_excel('movies_db.xlsx', sheet_name='financials') # reads the 'Sheet2' from the 'movies_db.xlsx' Excel file into a new DataFrame called df_movies_db_sheet2
df_movies_db_sheet2.head() # displays the first 5 rows of the df_movies_db_sheet2 DataFrame

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In the currency col, we can see USD, $$, Dollars. lets make all of them to USD

In [21]:
def std_currency(x):
    if x == "Dollars" or x == "$$":
        return "USD"
    else:
        return x

df_movies_db_financials = pd.read_excel('movies_db.xlsx', sheet_name='financials', converters={
    'currency': std_currency
})

df_movies_db_financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

we have fixed a issue in our sheet, now lets merge the financial sheet with movies sheet, we know the movie_id

In [22]:
df_merged_moviesAndFinancials = pd.merge(df_movies_db, df_movies_db_financials, on='movie_id') # merges the df_movies_db and df_movies_db_financials DataFrames based on the 'movie_id' column and creates a new DataFrame called df_merged_moviesAndFinancials
df_merged_moviesAndFinancials.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.0,670.0,Millions,USD

We can make a new excel file with this new data frame

In [23]:
df_merged_moviesAndFinancials.to_excel('merged_movies_and_financials.xlsx', sheet_name='merged_data', index=False)

# saves the df_merged_moviesAndFinancials DataFrame to a new Excel file named 'merged_movies_and_financials.xlsx' without including the index column

## Handling Missing Data

We data we find in real life is not always complete there may be many fields that contains trash, empty or random values, if we do not treat(handle) these values they will effect our final results.

The file `weather_data.csv` contains such values, lets see how we van handle them

In [24]:
df = pd.read_csv("weather_data.csv")
df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         28.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

We can see multiple fields containing `NaN` values, in real world a user might input random values like 999 or 69 in temprature field which will have a big impact on our analysis, like our avg(temprature) value will increase drastically.

In [25]:
df["day"].dtype

- type convert

    The values of day cols are of string type, we need them to be of  datatype - date

In [26]:
df["day"] = pd.to_datetime(df["day"])

In [27]:
type(df.temperature[0])

numpy.float64

- Fill NaN values

In [28]:
df_eg = df.fillna('0') # Replaces NaN values with 0
df_eg

         day temperature windspeed   event
0 2017-01-01        32.0       6.0    Rain
1 2017-01-04           0       9.0   Sunny
2 2017-01-05        28.0         0    Snow
3 2017-01-06           0       7.0       0
4 2017-01-07        32.0         0    Rain
5 2017-01-08           0         0   Sunny
6 2017-01-09           0         0       0
7 2017-01-10        34.1       8.1  Cloudy
8 2017-01-11        40.0      12.0   Sunny

Ideally we should be filling NaN values with something meaningfull, like avg, mean, min, max, etc to make sure we can better overall results from our analysis

In [29]:
df.fillna({
    'temperature' : df.temperature.mean(),
    'windspeed' : df.windspeed.mean(),
    'event' : "Regular"
})

         day  temperature  windspeed    event
0 2017-01-01        32.00       6.00     Rain
1 2017-01-04        33.22       9.00    Sunny
2 2017-01-05        28.00       8.42     Snow
3 2017-01-06        33.22       7.00  Regular
4 2017-01-07        32.00       8.42     Rain
5 2017-01-08        33.22       8.42    Sunny
6 2017-01-09        33.22       8.42  Regular
7 2017-01-10        34.10       8.10   Cloudy
8 2017-01-11        40.00      12.00    Sunny

One other approach is to fill NaN values with the values of the previous field - fill forward

In [30]:
df.ffill()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

Backward fill

In [31]:
df.bfill()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.1    Rain
5 2017-01-08         34.1        8.1   Sunny
6 2017-01-09         34.1        8.1  Cloudy
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [32]:
df.bfill(axis=1)

# Fills sideways i.e along cols

                   day temperature windspeed   event
0  2017-01-01 00:00:00        32.0       6.0    Rain
1  2017-01-04 00:00:00         9.0       9.0   Sunny
2  2017-01-05 00:00:00        28.0      Snow    Snow
3  2017-01-06 00:00:00         7.0       7.0     NaN
4  2017-01-07 00:00:00        32.0      Rain    Rain
5  2017-01-08 00:00:00       Sunny     Sunny   Sunny
6  2017-01-09 00:00:00         NaN       NaN     NaN
7  2017-01-10 00:00:00        34.1       8.1  Cloudy
8  2017-01-11 00:00:00        40.0      12.0   Sunny

- Interepolation

`interpolate()` method can be used to fill missing (NaN) numerical data in a Series or DataFrame by estimating values between known data points. 

***Does not work on str***

In [33]:
df.select_dtypes(include=['number', 'datetime']).interpolate()

# By default the interpolate() assumes a linear relationship, we can chagne this method.

         day  temperature  windspeed
0 2017-01-01         32.0      6.000
1 2017-01-04         30.0      9.000
2 2017-01-05         28.0      8.000
3 2017-01-06         30.0      7.000
4 2017-01-07         32.0      7.275
5 2017-01-08         32.7      7.550
6 2017-01-09         33.4      7.825
7 2017-01-10         34.1      8.100
8 2017-01-11         40.0     12.000

- **Delete/Drop** the rows with NaN Values

If the rows with NaN values are insignificant, we can drop and to avoid the hassle

In [34]:
df.dropna()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [35]:
df.select_dtypes(exclude=["datetime"]).dropna(how="all")
# Drops rows with where all fields are NaN

   temperature  windspeed   event
0         32.0        6.0    Rain
1          NaN        9.0   Sunny
2         28.0        NaN    Snow
3          NaN        7.0     NaN
4         32.0        NaN    Rain
5          NaN        NaN   Sunny
7         34.1        8.1  Cloudy
8         40.0       12.0   Sunny

In [36]:
df.dropna(thresh=2)
# only keeps rows with atleat 2 filds with not nan values.

# We can chagne axis to drop cols

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [37]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

## Replace Values

As we discussed earlier, in real world data some fileds can NaN but in many cases these fileds are filled with some random values, we will discuss how to fix them

In [38]:
df = pd.read_csv("weather_data2.csv")
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

We can see many fields contain -99999, if we were to find avg temp without handling these values, we will get unexpected results.

In [39]:
df.replace([-99999, - 88888], 0)

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017            0          7     Sunny
2  1/3/2017           28          0      Snow
3  1/4/2017            0          7  no event
4  1/5/2017           32          0      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34          0  no event

We can replace these values to Nan using numPy

In [40]:
import numpy as np

df.replace([-99999], np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0   -88888.0  no event

- Columns Wise replace

In [41]:
df.replace({
    "temperature" : -99999,
    "windspeed" : -99999,
    "event" : "no event",
}, np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0   -88888.0    NaN

- replace mappings

In [43]:
df.replace({
    -99999: np.nan,
    -88888 : np.nan,
    "no event" : "What a Joke"
})

        day  temperature  windspeed        event
0  1/1/2017         32.0        6.0         Rain
1  1/2/2017          NaN        7.0        Sunny
2  1/3/2017         28.0        NaN         Snow
3  1/4/2017          NaN        7.0  What a Joke
4  1/5/2017         32.0        NaN         Rain
5  1/6/2017         31.0        2.0        Sunny
6  1/6/2017         34.0        NaN  What a Joke

## Grouping Data

Consider the data set below

In [44]:
df = pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

We can see in cities column, we have same cities appearing multiple times.

Let's say we have to find min/max temprature in a particular city or we have to do some analysis to a particular city.

We can use `groupby()` method to group data by one or more **keys**(like cities)

In [46]:
g = df.groupby("city")
g

return a groupby object which is iterable

In [52]:
for city, data in g:
    print(city)
    print(data)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

As we can see, in our object `g`, in each iteration which have 2 parts:
1. Key - `city` 
2. dataframe-`data`.

we can furher unpack the df `data`  to access specific cols and fields

In [54]:
for city, data in g:
    print(city)
    print(data.temperature.max())

mumbai
92
new york
36
paris
54